Repository 0xOpenBytes/ios-base, pull requests merged in 2023-02, with the labels that each got.

#19 Add Acknowledgment View with current dependencies
  base/App/Home/HomeScreen.swift
  base/App/Views/AcknowledgmentView.swift
Labels: enhancement

#29 Readme Changes
  README.md
Labels: documentation

#32 Add regex check for correct name
  rename.sh
Labels: enhancement

#31 Remove extra newline
  Swish/Sources/ProjectLib/Resources/OpenBytesHeader.txt
  Swish/Sources/ProjectLib/Resources/StandardHeader.txt
Labels: bug
